### ISSUE TITLE
Add CLI testing guide

### ISSUE THREAD

**Issue by drorrose** [greenpress/docs#29]
Generate a guide with a specific title for each section (based on feature) that contains the following (ordered) instructions:

1. git clone -b compose-changes https://github.com/greenpress/greenpress-cli.git
2. cd greenpress-cli && npm install && sudo npm link
3. cd ..
4. greenpress missing - check if git, node, docker and docker-compose are presented in command's output
5. greenpress create my-app
6. cd my-app
7. change auth version to 1.0.10 in package.json/dependencies
8. greenpress upgrade - check that an upgrade for auth is suggested and that no upgrade for the rest is suggested
9. greenpress service create admin,assets - check that a dev directory is created with admin and assets repos cloned in it
10. greenpress start - check that app is running correctly (try to connect to the app on 0.0.0.0:3000)
11. greenpress populate - check that category, posts and admin credentials for admin panel are created correctly
12. greenpress stop
13. greenpress start dev -l admin,assets - check that greenpress.local.env contains ADMIN_CWD and ASSETS_CWD that are equal to dev/service-name and that the application is indeed running correctly

**Comment by davidmeirlevy** [comment]
Is that a guide on how to test the CLI to see if it works in different OSs?
Maybe this task should be in the CLI to find us an automation tool to check all operating systems.

**Comment by drorrose** [comment]
@davidmeirlevy 
This series of operations describes how to check each and every feature of the CLI (excluding theme creation), OS independent. Finding an automation tool is great and I'm behind that 100%, but in case of manual testing following enhancements and bug fixes of specific features, or even new developers who want to get a test run with the CLI, such a guide may provide a more comprehensive context to how the CLI works and how to use it at first.

**Comment by davidmeirlevy** [comment]
Ok. Sounds great.
Let's add a tests/manual-tests.md file for it.

**Comment by davidmeirlevy** [comment]
approved.
also, @drorrose and @or-yam  - consider adding a `swimm.io` guide for the CLI as well.
